services:
  nonebot:
    image: ghcr.io/west2-online/fzuhelper-bot:edge
    container_name: fzuhelper-bot
    volumes:
      - ./data:/app/data
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      ENVIRONMENT: prod
      HOST: 0.0.0.0
      PORT: 8080
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:8080" ]
      interval: 120s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      - bot-network

  lagrange-onebot:
    image: ghcr.io/lagrangedev/lagrange.onebot:edge
    container_name: lagrange-onebot
    volumes:
      - ./data:/app/data
    environment:
      - UID=${UID:-1000}
      - GID=${GID:-1000}
    restart: unless-stopped
    tty: true
    stdin_open: true
    networks:
      - bot-network
    depends_on:
      nonebot:
        condition: service_healthy

networks:
  bot-network:
    driver: bridge